const OurTeam = [
    {
        avatar: '/static/images/teamAvatar/saitama.jpg',
        name: 'Quốc Đạt',
        jobTitle: 'Lớp trưởng',
        spoken: 'Khát khao, ước ao có một cái đầu đẹp ',
        github: '',
        facebook: '',
        twitter: '',
    },
    {
        avatar: '/static/images/teamAvatar/sakura.jpg',
        name: 'Phương Thảo',
        jobTitle: 'Siêu nhân Gao',
        spoken: 'Thích hái sao nhưng vì chiều cao nên muốn thành siêu nhân gao.',
        github: '',
        facebook: '',
        twitter: '',
    },
    {
        avatar: '/static/images/teamAvatar/naruto.jpg',
        name: 'Quốc Thắng',
        jobTitle: 'Hokage',
        spoken: 'Thích tắm nắng, hay nói lăng nhăng, tính thẳng thắn.Ga lăng, tài năng.',
        github: 'https://github.com/waribiki95',
        facebook: 'https://www.facebook.com/kobietthenaonua',
        twitter: '',
    },
    {
        avatar: '/static/images/teamAvatar/midoriya.png',
        name: 'Ngọc Tuyền',
        jobTitle: 'Hộ sản',
        spoken: 'Yêu màu tím, thích màu hồng và ghét sự giả dối',
        github: '',
        facebook: '',
        twitter: '',
    },
    {
        avatar: '/static/images/teamAvatar/zoro.jpg',
        name: 'Mạnh Cường',
        jobTitle: 'Kiếm sĩ',
        spoken: 'Hay lạc đường, thích ăn thịt nướng, tương tư meo meo',
        github: '',
        facebook: '',
        twitter: '',
    },
    {
        avatar: '/static/images/teamAvatar/songoku.jpg',
        name: 'Hoàng Nam',
        jobTitle: 'Thợ trang điểm',
        spoken: 'Tham lam, hay nói xàm xàm, chuyên tám, thích ăn cam.',
        github: '',
        facebook: '',
        twitter: '',
    },
    {
        avatar: '/static/images/teamAvatar/sanji.jpg',
        name: 'Quang Trường',
        jobTitle: 'Xã hội đen',
        spoken: 'Thường khóc nhè, hay tè dầm, thích ăn nấm.',
        github: '',
        facebook: '',
        twitter: '',
    },
]
export default OurTeam;