const OurTeamFake = [
    {
        avatar: '/static/images/teamAvatar/saitamaFake.jpg',
        name: 'Quốc Đạt',
        jobTitle: 'Chủ tịch HĐQT',
        spoken: '    ',
        github: '',
        facebook: '',
        twitter: '',
    },
    {
        avatar: '/static/images/teamAvatar/sakuraFake.jpeg',
        name: 'Phương Thảo',
        jobTitle: 'Thư Ký',
        spoken: '',
        github: '',
        facebook: '',
        twitter: '',
    },
    {
        avatar: '/static/images/teamAvatar/narutoFake.jpg',
        name: 'Quốc Thắng',
        jobTitle: 'Develop',
        spoken: 'Hãy giỏi đến mức người khác không thể phớt lờ bạn.',
        github: 'https://github.com/waribiki95',
        facebook: 'https://www.facebook.com/kobietthenaonua',
        twitter: '',
    },
    {
        avatar: '/static/images/teamAvatar/midoriyaFake.jpg',
        name: 'Ngọc Tuyền',
        jobTitle: 'Hộ sản',
        spoken: '',
        github: '',
        facebook: '',
        twitter: '',
    },
    {
        avatar: '/static/images/teamAvatar/zoroFake.jpg',
        name: 'Mạnh Cường',
        jobTitle: '',
        spoken: '',
        github: '',
        facebook: '',
        twitter: '',
    },
    {
        avatar: '/static/images/teamAvatar/songokuFake.jpg',
        name: 'Hoàng Nam',
        jobTitle: '',
        spoken: '',
        github: '',
        facebook: '',
        twitter: '',
    },
    {
        avatar: '/static/images/teamAvatar/sanjiFake.jpg',
        name: 'Quang Trường',
        jobTitle: '',
        spoken: '',
        github: '',
        facebook: '',
        twitter: '',
    },
]
export default OurTeamFake;